language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: ./vendor/bin/tester -c ./tests/php.ini ./tests/