language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - TESTER_PHP_BIN="php"
  - TESTER_PHP_BIN="php-cgi"

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - php: hhvm
      env: TESTER_PHP_BIN="php-cgi"

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source --dev

before_script:
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - mysql -u root -e 'CREATE DATABASE testbase;'
  - mysql -u root testbase < tests/testbase.sql

script: ./vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/php.ini ./tests/