language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - TESTER_PHP_BIN="php"
  - TESTER_PHP_BIN="php-cgi"

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - php: hhvm
      env: TESTER_PHP_BIN="php-cgi"

install:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

# -c ./tests/php.ini
script: ./vendor/bin/tester -p $TESTER_PHP_BIN ./tests/