language: php

php:
  - 5.3.7
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: ./vendor/bin/tester -c ./tests/php.ini ./tests/